export const blogActionTypes = {
    BLOG_DATA_INITIATE: "BLOG_DATA_INITIATE",
    BLOG_DATA_SUCCESS: "BLOG_DATA_SUCCESS",
    BLOG_DATA_FAILURE: "BLOG_DATA_FAILURE",
    BLOG_DATA_RESET: "BLOG_DATA_RESET"
}
