export const userActionTypes = {
    USER_DATA_INITIATE: "USER_DATA_INITIATE",
    USER_DATA_SUCCESS: "USER_DATA_SUCCESS",
    USER_DATA_FAILURE: "USER_DATA_FAILURE",
    USER_DATA_RESET: "USER_DATA_RESET"
}